### ISSUE TITLE
Template not refreshed upon Build/reload

### ISSUE THREAD

**Issue by cjvanlissa** [rstudio/ptexamples#1]
When building/reinstalling package with an Rstudio project template, the template is not refreshed. Rebooting Rstudio does not work either, and neither does rebooting the computer. Pushing to Github and running devtools::install_github("mytemplatepackage") does work, but is very time consuming. Am I missing something?

Thank you for this feature!

**Comment by kevinushey** [comment]
This is surprising to me -- the IDE reindexes any available project templates every time the R session is restarted, so that would seem to imply that the template itself is actually stale.

Also: I was initially able to reproduce this, but then it seemed to go away later (installing the package as normal would update the template in the current RStudio instance). So, I don't have any great ideas what's going on :-/

**Comment by cjvanlissa** [comment]
This was solved by your response to my other Issue report: renv was initialized on a superordinate folder to the project I was working in, thereby affecting all lower level folders. Thank you!

**Comment by kevinushey** [comment]
Aha, good to hear. Thanks!
